# Generated by Django 5.0.3 on 2024-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField()),
                ('client', models.UUIDField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
