# Generated by Django 5.1.1 on 2024-09-30 16:15

import backend.models.model_cache
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareTurnStileCache',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=backend.models.model_cache.get_current_utc_time)),
            ],
        ),
        migrations.CreateModel(
            name='RequestCache',
            fields=[
                ('room', models.TextField()),
                ('client', models.UUIDField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=backend.models.model_cache.get_current_utc_time)),
            ],
        ),
        migrations.CreateModel(
            name='SocketRequestChapterQueueCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('socket_id', models.UUIDField()),
                ('channel_name', models.TextField()),
                ('source', models.TextField()),
                ('chapter_id', models.TextField()),
                ('options', models.JSONField()),
                ('datetime', models.DateTimeField(default=backend.models.model_cache.get_current_utc_time)),
            ],
        ),
    ]
