# Generated by Django 5.1.1 on 2024-09-25 12:17

import backend.module.utils.date_utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareTurnStileCache',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=backend.module.utils.date_utils.utc_time.get)),
            ],
        ),
        migrations.CreateModel(
            name='RequestCache',
            fields=[
                ('room', models.TextField()),
                ('client', models.UUIDField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=backend.module.utils.date_utils.utc_time.get)),
            ],
        ),
        migrations.CreateModel(
            name='SocketDownloadChapterQueueCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.TextField()),
                ('channel', models.TextField()),
                ('source', models.TextField()),
                ('chapter_id', models.TextField()),
                ('datetime', models.DateTimeField(default=backend.module.utils.date_utils.utc_time.get)),
            ],
        ),
    ]
