# Generated by Django 5.1.1 on 2024-12-01 11:38

import backend.models.model_1
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebscrapeGetCoverCache',
            fields=[
                ('file_path', models.TextField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('comic_id', models.TextField()),
                ('cover_id', models.TextField()),
                ('datetime', models.DateTimeField(default=backend.models.model_1.get_current_utc_time)),
            ],
        ),
    ]
