# Generated by Django 5.0.3 on 2024-09-13 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcache',
            name='id',
        ),
        migrations.AlterField(
            model_name='requestcache',
            name='client',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
