# Generated by Django 5.1.1 on 2024-10-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_socketrequestchapterqueuecache_comic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketrequestchapterqueuecache',
            name='chapter_idx',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
