# Generated by Django 5.0.3 on 2024-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_requestcache_id_alter_requestcache_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcache',
            name='client',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
