# Generated by Django 5.0.3 on 2024-09-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_requestcache_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcache',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
