# Generated by Django 5.1.1 on 2024-09-17 12:51

import backend.module.utils.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_cloudflareturnstilecache_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudflareturnstilecache',
            name='datetime',
            field=models.DateTimeField(default=backend.module.utils.date_utils.utc_time.get),
        ),
        migrations.AlterField(
            model_name='cloudflareturnstilecache',
            name='token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requestcache',
            name='datetime',
            field=models.DateTimeField(default=backend.module.utils.date_utils.utc_time.get),
        ),
    ]
