# Generated by Django 5.1.1 on 2024-12-07 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_requestwebscrapegetcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestwebscrapegetcache',
            name='page',
        ),
        migrations.AddField(
            model_name='requestwebscrapegetcache',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
