version: "3.8"
services:
  manga_image_translator:
    image: zyddnys/manga-image-translator
    container_name: manga_image_translator_gpu
    command: --verbose --log-web --mode web --use-inpainting --use-cuda --host=0.0.0.0 --port=5003
    volumes:
      - ./../../translate_demo.py:/app/translate_demo.py
      - facehuggingcache:/root/.cache/huggingface/
    ports:
      - 5003:5003
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  facehuggingcache: